
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("217d0a68-53b8-4700-96c8-cdc8d4726887")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("DatabaseProjectModel", "FK_Card_MEMBER", "MEMBER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(MEMBER), "Card", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Card), True)>
<Assembly: EdmRelationshipAttribute("DatabaseProjectModel", "FK_Movement_Card", "Card", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Card), "Movement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Movement), True)>
<Assembly: EdmRelationshipAttribute("DatabaseProjectModel", "FK_Movement_Movement", "MEMBER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(MEMBER), "Movement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Movement), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class DatabaseProjectEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new DatabaseProjectEntities object using the connection string found in the 'DatabaseProjectEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=DatabaseProjectEntities", "DatabaseProjectEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new DatabaseProjectEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "DatabaseProjectEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new DatabaseProjectEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "DatabaseProjectEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Cards() As ObjectSet(Of Card)
        Get
            If (_Cards Is Nothing) Then
                _Cards = MyBase.CreateObjectSet(Of Card)("Cards")
            End If
            Return _Cards
        End Get
    End Property

    Private _Cards As ObjectSet(Of Card)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MEMBERs() As ObjectSet(Of MEMBER)
        Get
            If (_MEMBERs Is Nothing) Then
                _MEMBERs = MyBase.CreateObjectSet(Of MEMBER)("MEMBERs")
            End If
            Return _MEMBERs
        End Get
    End Property

    Private _MEMBERs As ObjectSet(Of MEMBER)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Movements() As ObjectSet(Of Movement)
        Get
            If (_Movements Is Nothing) Then
                _Movements = MyBase.CreateObjectSet(Of Movement)("Movements")
            End If
            Return _Movements
        End Get
    End Property

    Private _Movements As ObjectSet(Of Movement)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Cards EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCards(ByVal card As Card)
        MyBase.AddObject("Cards", card)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MEMBERs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMEMBERs(ByVal mEMBER As MEMBER)
        MyBase.AddObject("MEMBERs", mEMBER)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Movements EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMovements(ByVal movement As Movement)
        MyBase.AddObject("Movements", movement)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DatabaseProjectModel", Name:="Card")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Card
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Card object.
    ''' </summary>
    ''' <param name="card_id">Initial value of the card_id property.</param>
    ''' <param name="card_no">Initial value of the card_no property.</param>
    Public Shared Function CreateCard(card_id As Global.System.Decimal, card_no As Global.System.String) As Card
        Dim card as Card = New Card
        card.card_id = card_id
        card.card_no = card_no
        Return card
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property card_id() As Global.System.Decimal
        Get
            Return _card_id
        End Get
        Set
            If (_card_id <> Value) Then
                Oncard_idChanging(value)
                ReportPropertyChanging("card_id")
                _card_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("card_id")
                Oncard_idChanged()
            End If
        End Set
    End Property

    Private _card_id As Global.System.Decimal
    Private Partial Sub Oncard_idChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub Oncard_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property card_no() As Global.System.String
        Get
            Return _card_no
        End Get
        Set
            Oncard_noChanging(value)
            ReportPropertyChanging("card_no")
            _card_no = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("card_no")
            Oncard_noChanged()
        End Set
    End Property

    Private _card_no As Global.System.String
    Private Partial Sub Oncard_noChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncard_noChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property customer_id() As Nullable(Of Global.System.Int32)
        Get
            Return _customer_id
        End Get
        Set
            Oncustomer_idChanging(value)
            ReportPropertyChanging("customer_id")
            _customer_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("customer_id")
            Oncustomer_idChanged()
        End Set
    End Property

    Private _customer_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncustomer_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncustomer_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property card_type() As Global.System.String
        Get
            Return _card_type
        End Get
        Set
            Oncard_typeChanging(value)
            ReportPropertyChanging("card_type")
            _card_type = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("card_type")
            Oncard_typeChanged()
        End Set
    End Property

    Private _card_type As Global.System.String
    Private Partial Sub Oncard_typeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncard_typeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property start_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _start_date
        End Get
        Set
            Onstart_dateChanging(value)
            ReportPropertyChanging("start_date")
            _start_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("start_date")
            Onstart_dateChanged()
        End Set
    End Property

    Private _start_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onstart_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onstart_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property end_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _end_date
        End Get
        Set
            Onend_dateChanging(value)
            ReportPropertyChanging("end_date")
            _end_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("end_date")
            Onend_dateChanged()
        End Set
    End Property

    Private _end_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onend_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onend_dateChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DatabaseProjectModel", "FK_Card_MEMBER", "MEMBER")>
    Public Property MEMBER() As MEMBER
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MEMBER)("DatabaseProjectModel.FK_Card_MEMBER", "MEMBER").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MEMBER)("DatabaseProjectModel.FK_Card_MEMBER", "MEMBER").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MEMBERReference() As EntityReference(Of MEMBER)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MEMBER)("DatabaseProjectModel.FK_Card_MEMBER", "MEMBER")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of MEMBER)("DatabaseProjectModel.FK_Card_MEMBER", "MEMBER", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DatabaseProjectModel", "FK_Movement_Card", "Movement")>
     Public Property Movements() As EntityCollection(Of Movement)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Movement)("DatabaseProjectModel.FK_Movement_Card", "Movement")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Movement)("DatabaseProjectModel.FK_Movement_Card", "Movement", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DatabaseProjectModel", Name:="MEMBER")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MEMBER
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MEMBER object.
    ''' </summary>
    ''' <param name="mEMBER_ID">Initial value of the MEMBER_ID property.</param>
    Public Shared Function CreateMEMBER(mEMBER_ID As Global.System.Int32) As MEMBER
        Dim mEMBER as MEMBER = New MEMBER
        mEMBER.MEMBER_ID = mEMBER_ID
        Return mEMBER
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MEMBER_ID() As Global.System.Int32
        Get
            Return _MEMBER_ID
        End Get
        Set
            If (_MEMBER_ID <> Value) Then
                OnMEMBER_IDChanging(value)
                ReportPropertyChanging("MEMBER_ID")
                _MEMBER_ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("MEMBER_ID")
                OnMEMBER_IDChanged()
            End If
        End Set
    End Property

    Private _MEMBER_ID As Global.System.Int32
    Private Partial Sub OnMEMBER_IDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnMEMBER_IDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MEMBER_NAME() As Global.System.String
        Get
            Return _MEMBER_NAME
        End Get
        Set
            OnMEMBER_NAMEChanging(value)
            ReportPropertyChanging("MEMBER_NAME")
            _MEMBER_NAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MEMBER_NAME")
            OnMEMBER_NAMEChanged()
        End Set
    End Property

    Private _MEMBER_NAME As Global.System.String
    Private Partial Sub OnMEMBER_NAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMEMBER_NAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MEMBER_LASTNAME() As Global.System.String
        Get
            Return _MEMBER_LASTNAME
        End Get
        Set
            OnMEMBER_LASTNAMEChanging(value)
            ReportPropertyChanging("MEMBER_LASTNAME")
            _MEMBER_LASTNAME = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MEMBER_LASTNAME")
            OnMEMBER_LASTNAMEChanged()
        End Set
    End Property

    Private _MEMBER_LASTNAME As Global.System.String
    Private Partial Sub OnMEMBER_LASTNAMEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMEMBER_LASTNAMEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MEMBER_TYPE() As Global.System.String
        Get
            Return _MEMBER_TYPE
        End Get
        Set
            OnMEMBER_TYPEChanging(value)
            ReportPropertyChanging("MEMBER_TYPE")
            _MEMBER_TYPE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MEMBER_TYPE")
            OnMEMBER_TYPEChanged()
        End Set
    End Property

    Private _MEMBER_TYPE As Global.System.String
    Private Partial Sub OnMEMBER_TYPEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMEMBER_TYPEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MEMBER_TEL() As Global.System.String
        Get
            Return _MEMBER_TEL
        End Get
        Set
            OnMEMBER_TELChanging(value)
            ReportPropertyChanging("MEMBER_TEL")
            _MEMBER_TEL = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MEMBER_TEL")
            OnMEMBER_TELChanged()
        End Set
    End Property

    Private _MEMBER_TEL As Global.System.String
    Private Partial Sub OnMEMBER_TELChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMEMBER_TELChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MEMBER_CITIZEN_CODE() As Global.System.String
        Get
            Return _MEMBER_CITIZEN_CODE
        End Get
        Set
            OnMEMBER_CITIZEN_CODEChanging(value)
            ReportPropertyChanging("MEMBER_CITIZEN_CODE")
            _MEMBER_CITIZEN_CODE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MEMBER_CITIZEN_CODE")
            OnMEMBER_CITIZEN_CODEChanged()
        End Set
    End Property

    Private _MEMBER_CITIZEN_CODE As Global.System.String
    Private Partial Sub OnMEMBER_CITIZEN_CODEChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMEMBER_CITIZEN_CODEChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MEMBER_ADDRESS() As Global.System.String
        Get
            Return _MEMBER_ADDRESS
        End Get
        Set
            OnMEMBER_ADDRESSChanging(value)
            ReportPropertyChanging("MEMBER_ADDRESS")
            _MEMBER_ADDRESS = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MEMBER_ADDRESS")
            OnMEMBER_ADDRESSChanged()
        End Set
    End Property

    Private _MEMBER_ADDRESS As Global.System.String
    Private Partial Sub OnMEMBER_ADDRESSChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMEMBER_ADDRESSChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DatabaseProjectModel", "FK_Card_MEMBER", "Card")>
     Public Property Cards() As EntityCollection(Of Card)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Card)("DatabaseProjectModel.FK_Card_MEMBER", "Card")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Card)("DatabaseProjectModel.FK_Card_MEMBER", "Card", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DatabaseProjectModel", "FK_Movement_Movement", "Movement")>
     Public Property Movements() As EntityCollection(Of Movement)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Movement)("DatabaseProjectModel.FK_Movement_Movement", "Movement")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Movement)("DatabaseProjectModel.FK_Movement_Movement", "Movement", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="DatabaseProjectModel", Name:="Movement")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Movement
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Movement object.
    ''' </summary>
    ''' <param name="movement_id">Initial value of the movement_id property.</param>
    Public Shared Function CreateMovement(movement_id As Global.System.Decimal) As Movement
        Dim movement as Movement = New Movement
        movement.movement_id = movement_id
        Return movement
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property movement_id() As Global.System.Decimal
        Get
            Return _movement_id
        End Get
        Set
            If (_movement_id <> Value) Then
                Onmovement_idChanging(value)
                ReportPropertyChanging("movement_id")
                _movement_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("movement_id")
                Onmovement_idChanged()
            End If
        End Set
    End Property

    Private _movement_id As Global.System.Decimal
    Private Partial Sub Onmovement_idChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub Onmovement_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property start_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _start_date
        End Get
        Set
            Onstart_dateChanging(value)
            ReportPropertyChanging("start_date")
            _start_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("start_date")
            Onstart_dateChanged()
        End Set
    End Property

    Private _start_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onstart_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onstart_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property end_date() As Nullable(Of Global.System.DateTime)
        Get
            Return _end_date
        End Get
        Set
            Onend_dateChanging(value)
            ReportPropertyChanging("end_date")
            _end_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("end_date")
            Onend_dateChanged()
        End Set
    End Property

    Private _end_date As Nullable(Of Global.System.DateTime)
    Private Partial Sub Onend_dateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Onend_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property card_id() As Nullable(Of Global.System.Decimal)
        Get
            Return _card_id
        End Get
        Set
            Oncard_idChanging(value)
            ReportPropertyChanging("card_id")
            _card_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("card_id")
            Oncard_idChanged()
        End Set
    End Property

    Private _card_id As Nullable(Of Global.System.Decimal)
    Private Partial Sub Oncard_idChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub Oncard_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property customer_id() As Nullable(Of Global.System.Int32)
        Get
            Return _customer_id
        End Get
        Set
            Oncustomer_idChanging(value)
            ReportPropertyChanging("customer_id")
            _customer_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("customer_id")
            Oncustomer_idChanged()
        End Set
    End Property

    Private _customer_id As Nullable(Of Global.System.Int32)
    Private Partial Sub Oncustomer_idChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Oncustomer_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CAR_NO_OTHER() As Global.System.String
        Get
            Return _CAR_NO_OTHER
        End Get
        Set
            OnCAR_NO_OTHERChanging(value)
            ReportPropertyChanging("CAR_NO_OTHER")
            _CAR_NO_OTHER = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CAR_NO_OTHER")
            OnCAR_NO_OTHERChanged()
        End Set
    End Property

    Private _CAR_NO_OTHER As Global.System.String
    Private Partial Sub OnCAR_NO_OTHERChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCAR_NO_OTHERChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DatabaseProjectModel", "FK_Movement_Card", "Card")>
    Public Property Card() As Card
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Card)("DatabaseProjectModel.FK_Movement_Card", "Card").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Card)("DatabaseProjectModel.FK_Movement_Card", "Card").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CardReference() As EntityReference(Of Card)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Card)("DatabaseProjectModel.FK_Movement_Card", "Card")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Card)("DatabaseProjectModel.FK_Movement_Card", "Card", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("DatabaseProjectModel", "FK_Movement_Movement", "MEMBER")>
    Public Property MEMBER() As MEMBER
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MEMBER)("DatabaseProjectModel.FK_Movement_Movement", "MEMBER").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MEMBER)("DatabaseProjectModel.FK_Movement_Movement", "MEMBER").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MEMBERReference() As EntityReference(Of MEMBER)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MEMBER)("DatabaseProjectModel.FK_Movement_Movement", "MEMBER")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of MEMBER)("DatabaseProjectModel.FK_Movement_Movement", "MEMBER", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


